Update Gemfile to version dry-configurable
- was causing NoMethodError: undefined method `map' for nil:NilClass

/home/travis/.rvm/gems/ruby-2.6.2/gems/warden-jwt_auth-0.3.6/lib/warden/jwt_auth.rb:89:in `upcase_first_items'

- found a solution here https://stackoverflow.com/questions/60470873/why-i-have-an-error-when-i-generate-jwt-blacklist-model-for-rails-5/60491838#60491838?newreg=7071f31f48194c26875f49f9b463c008

Co-authored-by: Mike Aono <aonomike@gmail.com>